### ISSUE TITLE
Add a note that internals were copied from voltage

### ISSUE THREAD

**Issue by EnokiUN** [Pysics/Revoltaic#6]

**Comment by b1ue64** [comment]
the MIT licence actually requires that this person puts a copy of the original notice somewhere
therefore, he is breaking the licence

**Comment by EnokiUN** [comment]
> the MIT licence actually requires that this person puts a copy of the original notice somewhere therefore, he is breaking the licence

Exactly,

Also an additional tip: change the name of the lib, author name, support server url and github url from ws.py line 87 and on, also consider changing the logo if you can :trollface:

**Comment by Pysics** [comment]
I was just testing some stuff. I am planning to delete this project anyway.
